#!/usr/bin/env node
/* The gauge — the smallest thing that can be a world, run against the shared suite.
   Every leak in docs/TAGS.md was found by READING the engine. Nobody had ever built a second
   world to find out which one a real pack hits FIRST, so this is that world: five tiles, two
   people, one room, in content/gauge/. It is not a game and is never linked from one. Its only
   job is to fail in the places a new game would fail, out loud, on every CI run.
   The shell is GENERATED from the public index rather than copied, because ~770 of its ~800
   lines must be identical (the shared suite reads about twenty element ids straight out of it)
   and a copy would rot silently the first time index.html changed. Every edit below asserts it
   actually matched: a String.replace that stops matching returns the input unchanged and would
   otherwise print success while testing the wrong thing.
   Run:  node test/gauge.js          */
const fs = require('fs'), path = require('path'), { execFileSync } = require('child_process');
const root = path.resolve(__dirname, '..');
const SCRIPTS = ['strings', 'quests.en', 'quests.es', 'npcs', 'maps', 'art', 'config'];

let h = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const edit = (what, re, to) => {
  const before = h;
  h = h.replace(re, to);
  if (h === before) throw new Error('the gauge shell can no longer be built from index.html: the "' + what + '" edit matched nothing. index.html changed shape — fix this generator, do not commit a hand-made copy.');
};

// the pack's own scripts, in the order the public shell loads Meridian's
edit('script tags',
  /<script src="content\/meridian\/strings\.js"><\/script>[\s\S]*?<script src="content\/meridian\/docs\.js"><\/script>/,
  SCRIPTS.map(s => '<script src="' + s + '.js"></script>').join('\n'));
// depth: content/gauge/index.html is two folders down from the root the public shell sits in
edit('engine paths', /<script src="(engine\/|vendor\/|qr\.js|frame-guard\.js)/g, '<script src="../../$1');
edit('font paths', /<link rel="stylesheet" href="vendor\/fonts\//, '<link rel="stylesheet" href="../../vendor/fonts/');
edit('shell stylesheet', /<link rel="stylesheet" href="shell\.css">/, '<link rel="stylesheet" href="../../shell.css">');   /* the page's look (#256) */
edit('touch icon', /<link rel="apple-touch-icon" href="icon-192\.png">/, '<link rel="apple-touch-icon" href="../../icon-192.png">');
edit('title', /<title>[^<]*<\/title>/, '<title>El Faro — the gauge pack</title>');
// a fixture must not claim to be an installable app, and must not fight the real one for a cache
edit('manifest', /<link rel="manifest"[^>]*>/, '<!-- no manifest: the gauge is a fixture, not an app -->');
edit('service worker', /<script src="sw-register\.js"><\/script>/, '<!-- no service worker: the gauge never installs one -->');

if (h.includes('content/meridian/')) throw new Error('the generated gauge shell still loads Meridian content');
SCRIPTS.forEach(s => { if (!h.includes('"' + s + '.js"')) throw new Error('the generated gauge shell never loads ' + s + '.js'); });

const shellPath = path.join(root, 'content', 'gauge', 'index.html');
fs.writeFileSync(shellPath, h);
console.log('gauge shell built from index.html (' + h.split('\n').length + ' lines, ' + SCRIPTS.length + ' pack scripts)');

/* ---------- THE SECOND GAUGE: the camera the owner actually plays (2026-09-22) ----------
   El Faro declares CAMERAS=["top","front"] and that line is LOAD-BEARING — it is the only proof in
   this repository that engine/boot.js skips a 149 KB library for a world that does not want 3D. So
   it is not flipped. A SECOND shell is generated beside it that declares all four, and the result
   is the first time anything here has measured what a brand-new world looks like in the camera the
   owner plays. Until today that answer was nobody's: every 3D demand the engine makes of a new pack
   — the shape library, the flat-tile audit, the bake, the contact shadow — was exercised only by
   the two games that already have art of their own.
   Generated, never committed, and every edit asserts it matched (docs/GAUGE.md: a String.replace
   that stops matching returns the input unchanged and would print success while testing the wrong
   thing). */
const cfgPath = path.join(root, 'content', 'gauge', 'config.js');
let cfg = fs.readFileSync(cfgPath, 'utf8');
const cedit = (what, re, to) => { const before = cfg; cfg = cfg.replace(re, to);
  if (cfg === before) throw new Error('the 3D gauge config can no longer be built: the "' + what + '" edit matched nothing in content/gauge/config.js — fix this generator, do not commit a hand-made copy.'); };
cedit('CAMERAS', /const CAMERAS=\[[^\]]*\];/, 'const CAMERAS=["top","front","iso","3d"];');
cedit('CAMDEF', /const CAMDEF="[^"]*";/, 'const CAMDEF="3d";');
cedit('storage prefix', /const STOREPFX="gauge";/, 'const STOREPFX="gauge3d";');
cfg = '/* GENERATED by test/gauge.js from content/gauge/config.js - never commit a copy.\n' +
      '   The same five-tile world, asked to stand up in all four cameras. */\n' + cfg;
if (!/\["top","front","iso","3d"\]/.test(cfg)) throw new Error('the 3D gauge config does not declare four cameras');
fs.writeFileSync(path.join(root, 'content', 'gauge', 'config-3d.js'), cfg);

let h3 = h;
{ const before = h3; h3 = h3.replace('<script src="config.js"></script>', '<script src="config-3d.js"></script>');
  if (h3 === before) throw new Error('the 3D gauge shell can no longer be built: it does not load config.js'); }
{ const before = h3; h3 = h3.replace(/<title>[^<]*<\/title>/, '<title>El Faro en 3D \u2014 the gauge pack, four cameras</title>');
  if (h3 === before) throw new Error('the 3D gauge shell has no title to replace'); }
if (h3.includes('"config.js"')) throw new Error('the 3D gauge shell still loads the two-camera config');
fs.writeFileSync(path.join(root, 'content', 'gauge', 'index-3d.html'), h3);
console.log('gauge 3D shell built beside it (four cameras, its own storage prefix)');

/* ---------- THE THIRD GAUGE: a new world that lays the ENGINE'S OWN furniture and takes it by name ----------
   The two shells above lay only letters of their own, so neither ever asked the question a world built on this
   engine actually asks first: "I lay the engine's desk, table, bookcase, stove and counter, its site sign, its
   marigold planters and its grass — I take every one of them from the engine's shape library by name — what do I
   get?" Until this shell nobody in this repository could answer that, because Meridian answers every one of those
   letters with a mesh of its own and so never takes the library's. The answer, measured on 2026-10-04: boxes with
   a photograph of the thing pasted on four faces and the lid, a sign that turns to face the camera like a cut-out,
   and flowers painted on the floor — which is what reads as 2D in a 3D camera, and why a fix made in one world never
   reached another.
   So this room lays nothing but the engine's letters (and its own wall), declares the letters it takes, and is held
   to the same shared suite as every other shell. Its standing demands are recorded in expected-lib.txt like the
   other two, and that file holds ONLY the ones a small room cannot meet: a line about a letter standing as a box,
   a picture, or not at all is a NEW demand and fails, which is how this shell keeps the library honest.
   Generated, never committed (.gitignore), and nothing below edits a file that ships: it reuses the gauge's people,
   words and quest, and writes its own map, art and config beside them. The people stand on lower-case letters the
   engine does not own, so neither of them is a counter.
   NINE TILES WIDE, like the other two shells, and that was measured: the first room was thirteen wide, wide enough
   that the top camera scrolls on a phone, and the suite's drone-card check (which waits 160 ms at each spot of a
   sweep) then read the card mid-move at one tile in two runs out of three on a loaded machine. Nothing in this
   room's job needs a camera that scrolls. And an open three-by-three in the west, with nothing tall south of it:
   the suite digs its dog's hole on the first such patch, and with the counters directly south of it the resting
   camera saw the counter and not the hole — a fact about this room's furniture, not about the engine. */
const LIBROOM = [
  'sssssssss',
  's...SSSVs',   /* a run of three bookcases, backs to the north wall, and a stove in the corner */
  's.......s',
  's....KKKs',   /* a run of three counters (the first is where the drawing puts the machine) */
  's......Ts',   /* a table */
  'sbbkgmXDs',   /* two planters in a run, a person, a tuft of grass, a person, the site sign, a desk */
  'sssssssss'];
const LIBTAKE = 'DTSKVXbg';
const libMaps = '/* GENERATED by test/gauge.js — never commit a copy. One room laying the engine\'s own letters. */\n' +
  'const WORLD_DEFS={lamp:' + JSON.stringify(LIBROOM) + '};\n' +
  'const PORTALS={};\n' +
  'const WNPC={lamp:{k:{npc:"kepa",q:[0]},m:{npc:"mira",q:[]}}};\n';
const libArt = '/* GENERATED by test/gauge.js — never commit a copy. The wall is this room\'s own; every other letter it lays\n' +
  '   is the engine\'s, drawn by the engine, and shaped (if at all) by the engine\'s library. Bookcases are not walked\n' +
  '   through here, which is this world\'s word to say, so S is solid. */\n' +
  'const SOLIDX="sS";\n' +
  'const TILEMETA={s:{lift:13,kind:"wall"}};\n' +
  'const TILEART={s:{top:function(x,y){ctx.fillStyle="#6E7078";ctx.fillRect(x,y,40,40);},side:function(x,y){ctx.fillStyle="#5A5C63";ctx.fillRect(x,y,40,40);}}};\n' +
  'const SHAPETAKE=' + JSON.stringify(LIBTAKE) + ';\n' +
  '/* and it keeps nothing as a picture on purpose, so a letter left flat here is a fault, not the shared baseline */\n' +
  'const FLAT_OK={letters:[],why:{}};\n';
let cfgLib = cfg;
{ const before = cfgLib; cfgLib = cfgLib.replace('const STOREPFX="gauge3d";', 'const STOREPFX="gaugelib";');
  if (cfgLib === before) throw new Error('the library gauge config can no longer be built: the 3D config has no "gauge3d" prefix to replace'); }
fs.writeFileSync(path.join(root, 'content', 'gauge', 'maps-lib.js'), libMaps);
fs.writeFileSync(path.join(root, 'content', 'gauge', 'art-lib.js'), libArt);
fs.writeFileSync(path.join(root, 'content', 'gauge', 'config-lib.js'), cfgLib);
let hl = h3;
[['maps.js', 'maps-lib.js'], ['art.js', 'art-lib.js'], ['config-3d.js', 'config-lib.js']].forEach(([a, b]) => {
  const before = hl; hl = hl.replace('<script src="' + a + '"></script>', '<script src="' + b + '"></script>');
  if (hl === before) throw new Error('the library gauge shell can no longer be built: the 3D shell does not load ' + a); });
{ const before = hl; hl = hl.replace(/<title>[^<]*<\/title>/, '<title>El Faro, amueblado — the gauge laying the engine’s own furniture</title>');
  if (hl === before) throw new Error('the library gauge shell has no title to replace'); }
['"maps.js"', '"art.js"', '"config.js"', '"config-3d.js"'].forEach(s => { if (hl.includes(s)) throw new Error('the library gauge shell still loads ' + s); });
fs.writeFileSync(path.join(root, 'content', 'gauge', 'index-lib.html'), hl);
console.log('gauge library shell built beside them (the engine\'s letters, taken by name: ' + LIBTAKE + ')');
if (process.argv.includes('--build-only')) process.exit(0);

/* The gauge does NOT chase green, and that is the whole point of it.
   Six of the shared suite's checks fail this pack for being SMALL rather than for being WRONG —
   "no facade has two windows", "no tall piece was found", "the check never ran". They are honest
   about it and they fail the build anyway, which means the suite advertised as runnable against
   ANY pack cannot be passed by the smallest pack that is a world. docs/NEW-WORLD.md §5 makes the
   shared suite step 3 and a minimal pack step 2, so today the gate rejects the thing the step
   before it produces.
   So this records what a new world is up against and fails when that CHANGES. A line that
   disappears means the template got easier — good, delete it here and say so. A line that appears
   means somebody made the engine harder to write a second game for, and it says so on the day it
   happens instead of in somebody's month two. */
/* A RUN THAT NEVER ENDS IS A RED, NOT A WAIT (#279). This file used to wait for the inner run with
   no limit at all. Twice on 2026-09-30, on a busy machine, the 3D run sat for eighteen minutes with
   its renderer at zero CPU until somebody stopped it by hand; on GitHub that is a pull request stuck
   at "running", not a clear red. Measured 2026-09-30: one inner run takes 11-15 s on a loaded
   four-core machine, and the whole CI step, both runs, takes 23 s; the re-run on that busy machine
   passed in 27 s. The limit is 180 s, more than six times that, so a slow machine is not failed for being
   slow and a stuck one fails inside three minutes, by name.
   SIGKILL, not the default SIGTERM: Playwright gives the child its own SIGTERM handler, and a child
   whose event loop is stuck never runs any handler, so a polite signal can leave this file waiting
   for ever, which is the bug. Planted that way (SIGTERM, a child stuck in a loop), this file was
   still waiting four minutes past its limit when an outside watchdog stopped it. */
const LIMIT_S = 180;
function measure(shell, expectedFile, label) {
const expectedPath = path.join(root, 'content', 'gauge', expectedFile);
let out = '';
const t0 = Date.now();
try {
  out = execFileSync('node', [path.join(root, 'test', 'engine.smoke.js'), '--index', shell],
    { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: LIMIT_S * 1000, killSignal: 'SIGKILL' });
} catch (e) {
  out = (e.stdout || '') + (e.stderr || '');
  if (e.code === 'ETIMEDOUT') {
    console.log('FAIL — ' + label + ' timed out: its engine checks (node test/engine.smoke.js --index ' + shell + ') were');
    console.log('still running after ' + Math.round((Date.now() - t0) / 1000) + ' s, where a normal run takes under 30 s, so they were stopped.');
    console.log('This is a hung run, not a finding about the engine: run it again, and if it hangs again, the');
    console.log('last thing it printed is where it stuck.');
    console.log('--- the last thing the inner run printed ---');
    console.log(out.trim().split('\n').slice(-12).join('\n') || '(it printed nothing at all)');
    return 1;
  }
}

const got = out.split('\n').filter(l => l.startsWith('- ')).map(l => l.slice(2).trim())
  // one line carries a live frame count; the number is noise, the fact is not
  .map(l => l.replace(/drawn \d+ time\(s\)/, 'drawn N time(s)')).sort();

/* A gauge that cannot RUN must never report that the template got easier.
   2026-09-16: the shared suite could not launch a browser (the container's chromium was a
   version behind what playwright-core resolves), so the inner run died before a single check
   fired. `got` came back empty, every expected line looked "no longer demanded", and this file
   printed six lines of GOOD NEWS about an engine it had never asked a question of. That is the
   silent zero this whole fixture exists to catch, happening inside the fixture — so it is now
   the first thing checked, and it fails differently, because "nothing to measure" is not a
   measurement (docs/GAUGE.md). */
if (!got.length) {
  console.log('FAIL — ' + label + ' never ran. The shared suite produced no findings at all, which is');
  console.log('not the same as finding nothing. This is a broken run, not an easier template.');
  console.log('Most often: no usable Chromium. Set CHROMIUM_PATH to a real binary and try again.');
  console.log('--- what the inner run actually said ---');
  console.log(out.trim().split('\n').slice(-20).join('\n') || '(it said nothing at all)');
  return 1;
}

if (!fs.existsSync(expectedPath)) {
  fs.writeFileSync(expectedPath, got.join('\n') + '\n');
  console.log(label + ': first run — recorded ' + got.length + ' standing demands in content/gauge/' + expectedFile);
  return 0;
}
const want = fs.readFileSync(expectedPath, 'utf8').split('\n').map(l => l.trim()).filter(Boolean).sort();
const gone = want.filter(l => !got.includes(l)), fresh = got.filter(l => !want.includes(l));

if (!gone.length && !fresh.length) {
  console.log('OK — ' + label + ': a five-tile, two-person, one-room world still boots, plays and meets the engine on the same ' + want.length + ' terms as before.');
  return 0;
}
console.log('FAIL — what the engine demands of a brand-new world has CHANGED (' + label + ').');
fresh.forEach(l => console.log('  NEW demand on every future game: ' + l));
gone.forEach(l => console.log('  no longer demanded (the template got easier — delete this line from content/gauge/' + expectedFile + ' and say so in the commit): ' + l));
return 1;
}

/* ALL THREE shells, every run. The two-camera one is the older measurement and the only proof that the
   library is skipped for a world that declined 3D; the four-camera one is the first time this
   repository has asked what a brand-new world costs in the camera the owner plays; the third is the
   only world here that takes the engine's furniture from its library rather than drawing its own. Any
   one failing fails the build, and none short-circuits another — a run that stops at the first failure
   tells you a third of what changed. */
const rc = measure('content/gauge/index.html', 'expected.txt', 'the gauge')
         | measure('content/gauge/index-3d.html', 'expected-3d.txt', 'the gauge in 3D')
         | measure('content/gauge/index-lib.html', 'expected-lib.txt', 'the gauge laying the engine\'s furniture');
process.exit(rc ? 1 : 0);
